steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args: [ "-c", "mkdir -p workspace/secrets && echo $$API_KEY > workspace/secrets/account_service_key.json" ]
  secretEnv: [ "API_KEY" ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args: [ "-c", "mkdir -p workspace/secrets && echo $$EMAIL_KEY > workspace/secrets/email_service_key.json" ]
  secretEnv: [ "EMAIL_KEY" ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args: [ "-c", "mkdir -p workspace/config && echo $$DB_SECRETS > workspace/config/config.json" ]
  secretEnv: [ "DB_SECRETS" ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args: [ "-c", "cd workspace && ls" ]
# admin microservice
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-admin/admin:latest', '-f', 'src/microservices/admin/gcp.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-admin/admin:latest']
# users microservice
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-users/users:latest', '-f', 'src/microservices/users/gcp.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-users/users:latest']
# file-management
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-file-management/file-management:latest', '-f', 'src/microservices/fileManagement/gcp.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-file-management/file-management:latest']
# notifications
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-notifications/notifications:latest', '-f', 'src/microservices/notifications/gcp.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-notifications/notifications:latest']
# third parties
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-third-parties/third-parties:latest', '-f', 'src/microservices/thirdParties/gcp.Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-third-parties/third-parties:latest']
# deployments
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'admin', '--image', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-admin/admin:latest', '--region', 'us-central1']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'users', '--image', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-users/users:latest', '--region', 'us-central1']
  # file management
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'file-management', '--image', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-file-management/file-management:latest', '--region', 'us-central1']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'notifications', '--image', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-notifications/notifications:latest', '--region', 'us-central1']
  # third parties
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'third-parties', '--image', 'us-east1-docker.pkg.dev/cali-mobility/cali-mobility-third-parties/third-parties:latest', '--region', 'us-central1']
availableSecrets:
  secretManager:
    - versionName: projects/85094745134/secrets/service_key/versions/2
      env: API_KEY
    - versionName: projects/85094745134/secrets/email_key/versions/1
      env: EMAIL_KEY
    - versionName: projects/85094745134/secrets/db_secrets/versions/1
      env: DB_SECRETS
options:
  logging: CLOUD_LOGGING_ONLY